using MyORM.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MyORM
{

    public class AutoGenerated : Attribute
    { }

    public class PrimaryKey : Attribute
    { }

    public class Table : Attribute
    {
        public Table() { }
        public Table(string name)
        {
            this.Name = name;
        }
        public string Name { get; set; }
    }

    public class Column : Attribute
    {
        public Column() { }
        public Column(string name)
        {
            this.Name = name;
        }
        public string Name { get; set; }
    }


    public class Join : Attribute
    {
        public Join() {
            this.Type = Jointype.INNER;
        }
        public Join(string ForeignKey,string Key)
        {
            this.ForeignKey = ForeignKey;
            this.Key = Key;
            this.Type = Jointype.INNER;
        }
        public Join(string ForeignKey, string Key, Jointype JoinType)
        {
            this.ForeignKey = ForeignKey;
            this.Key = Key;
            this.Type = JoinType;
        }
        public string ForeignKey { get; set; }
        public string Key { get; set; }

        public Jointype Type { get; set; }
    }

    public class AutoGeneratedNoDB : Attribute
    { }
}
